# fly.toml app configuration file generated for friendstube-streaming-helper on 2023-08-30T07:27:41+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "friendstube-streaming-helper"
primary_region = "sin"

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
